services:
  organizer-bot:
    build: .
    container_name: organizer-bot
    restart: always
    env_file:
      - .env
    volumes:
      - medication_data:/app/data

volumes:
  medication_data:
    driver: local
